# Generated by Django 3.1.14 on 2022-09-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenons',
            new_name='linenos',
        ),
    ]
